In [25]:
import numpy as np

In [26]:
arr = np.random.randint(1,40,10)
arr

array([20, 20, 18, 15, 11,  5, 19, 23, 20,  5], dtype=int32)

In [27]:
np.argsort(arr)

array([5, 9, 4, 3, 2, 6, 0, 1, 8, 7])

In [28]:
arr[np.argsort(arr)]

array([ 5,  5, 11, 15, 18, 19, 20, 20, 20, 23], dtype=int32)